apiVersion: v1
kind: Service
metadata:
  name: simple-devops-cicd-svc
spec:
  selector:
    app: simple-devops-cicd
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
